name: Generate Repository Cards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-card:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate CVE repository card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=Mr-Crux-Ansata&repo=cve-vulnerability-classifier&title_color=FF6B9D&text_color=FCECF3&icon_color=FF9FC2&bg_color=241B2F&border_color=FF6B9D&hide_border=false&border_radius=6&show_owner=false&description_lines_count=2
          path: assets/cve-vulnerability-classifier.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit card
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/cve-vulnerability-classifier.svg

          git diff --cached --quiet || git commit -m "Update repository card"

          git push
